version: '3.8'
services:
  web-api:
    container_name: web-api
    build:
      context: backend
      dockerfile: API/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db-server,1433;Database=nullam;User Id=sa;Password=Passw0rd1;TrustServerCertificate=True;
    networks:
      - internal

  db-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd1
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - internal

  web-ui:
    container_name: web-ui
    build:
      context: frontend/react-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - web-api
    networks:
      - internal

volumes:
  sqlvolume:

networks:
  internal:
